# Generated by Django 3.2.12 on 2026-01-20 21:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vs_ai', models.BooleanField(default=False)),
                ('fen', models.CharField(default='', max_length=100)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('PLAYING', 'Playing'), ('CHECKMATE', 'Checkmate'), ('STALEMATE', 'Stalemate'), ('DRAW', 'Draw'), ('RESIGNED', 'Resigned'), ('TIMEOUT', 'Timeout')], default='WAITING', max_length=10)),
                ('turn', models.CharField(choices=[('w', 'White'), ('b', 'Black')], default='w', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('DRAW', 'Draw'), ('RESIGNED', 'Resigned'), ('TIMEOUT', 'Timeout')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='game.game')),
            ],
        ),
    ]
