# Generated by Django 3.2.12 on 2026-01-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='updated_at',
            new_name='finished_at',
        ),
        migrations.AddField(
            model_name='game',
            name='black_clock',
            field=models.IntegerField(default=600000),
        ),
        migrations.AddField(
            model_name='game',
            name='white_clock',
            field=models.IntegerField(default=600000),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished')], default='WAITING', max_length=10),
        ),
    ]
