# Generated by Django 5.2.10 on 2026-02-06 17:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_auto_20260120_2241"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gameresult",
            name="game",
        ),
        migrations.RemoveField(
            model_name="gameresult",
            name="loser",
        ),
        migrations.RemoveField(
            model_name="gameresult",
            name="winner",
        ),
        migrations.CreateModel(
            name="GameResults",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vs_ai", models.BooleanField(default=False)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("CHECKMATE", "Checkmate"),
                            ("DRAW", "Draw"),
                            ("RESIGNED", "Resigned"),
                            ("TIMEOUT", "Timeout"),
                        ],
                        max_length=10,
                    ),
                ),
                ("finished_at", models.DateTimeField(auto_now=True)),
                (
                    "loser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_lost",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_black",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_as_black",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_white",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_as_white",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_won",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Game",
        ),
        migrations.DeleteModel(
            name="GameResult",
        ),
    ]
