export const GAME_ROOM_EVENTS = {
	STATE_SYNC: 'STATE_SYNC',
	STATE_SYNC_REQ: 'STATE_SYNC_REQ',
	CLOCK_TICK: 'CLOCK_TICK',
	PRESENCE: 'PRESENCE',

	MOVE_SUBMIT: 'MOVE_SUBMIT',
	MOVE_REJECTED: 'MOVE_REJECTED',

	CHAT_SEND: 'CHAT_SEND',
	CHAT_MESSAGE: 'CHAT_MESSAGE',

	RESIGN: 'RESIGN',
	ERROR: 'ERROR',
	GAME_OVER: 'GAME_OVER',
};

export const WS_STATUS = {
	CONNECTING: 'connecting',
	OPEN: 'open',
	CLOSED: 'closed',
	ERROR: 'error',
};