import json

en = {}
es = {}
fr = {}

data = [
    { "key": "toast.achievementUnlocked", "en": "Achievement unlocked", "es": "Logro desbloqueado", "fr": "Succès déverrouillé" },
    { "key": "footer.privacyPolicy", "en": "Privacy Policy", "es": "Política de privacidad", "fr": "Politique de confidentialité" },
    { "key": "footer.terms", "en": "Terms", "es": "Términos", "fr": "Conditions" },
    { "key": "menu.lobby", "en": "Lobby", "es": "Sala de espera", "fr": "Salon" },
    { "key": "menu.profile", "en": "Profile", "es": "Perfil", "fr": "Profil" },
    { "key": "menu.friends", "en": "Friends", "es": "Amigos", "fr": "Amis" },
    { "key": "menu.history", "en": "History", "es": "Historial", "fr": "Historique" },
    { "key": "menu.leaderboard", "en": "Leaderboard", "es": "Tabla de posiciones", "fr": "Classement" },
    { "key": "menu.title", "en": "Menu", "es": "Menú", "fr": "Menu" },
    { "key": "topbar.brandTitle", "en": "Checkmate Club", "es": "Checkmate Club", "fr": "Checkmate Club" },
    { "key": "topbar.brandSubtitle", "en": "A quiet room for sharp games, stubborn defenses and elegant blunders.", "es": "Una habitación tranquila para partidas intensas, defensas obstinadas y errores elegantes.", "fr": "Une pièce calme pour des parties acharnées, des défenses obstinées et des erreurs élégantes." },
    { "key": "topbar.logout", "en": "Logout", "es": "Cerrar sesión", "fr": "Déconnexion" },
    { "key": "topbar.login", "en": "Login", "es": "Iniciar sesión", "fr": "Connexion" },
    { "key": "topbar.register", "en": "Register", "es": "Registrarse", "fr": "S'inscrire" },
    { "key": "auth.register.title", "en": "Create account", "es": "Crear cuenta", "fr": "Créer un compte" },
    { "key": "auth.register.emailLabel", "en": "Email", "es": "Correo electrónico", "fr": "E-mail" },
    { "key": "auth.register.emailPlaceholder", "en": "Email", "es": "Correo electrónico", "fr": "E-mail" },
    { "key": "auth.register.usernameLabel", "en": "Username", "es": "Nombre de usuario", "fr": "Nom d'utilisateur" },
    { "key": "auth.register.usernamePlaceholder", "en": "Username", "es": "Nombre de usuario", "fr": "Nom d'utilisateur" },
    { "key": "auth.register.displayNameLabel", "en": "Display name", "es": "Nombre para mostrar", "fr": "Nom d'affichage" },
    { "key": "auth.register.displayNamePlaceholder", "en": "Display name", "es": "Nombre para mostrar", "fr": "Nom d'affichage" },
    { "key": "auth.register.passwordLabel", "en": "Password", "es": "Contraseña", "fr": "Mot de passe" },
    { "key": "auth.register.passwordPlaceholder", "en": "Password", "es": "Contraseña", "fr": "Mot de passe" },
    { "key": "auth.hidePassword", "en": "Hide password", "es": "Ocultar contraseña", "fr": "Masquer le mot de passe" },
    { "key": "auth.showPassword", "en": "Show password", "es": "Mostrar contraseña", "fr": "Afficher le mot de passe" },
    { "key": "auth.hide", "en": "Hide", "es": "Ocultar", "fr": "Masquer" },
    { "key": "auth.show", "en": "Show", "es": "Mostrar", "fr": "Afficher" },
    { "key": "auth.register.confirmPasswordLabel", "en": "Confirm password", "es": "Confirmar contraseña", "fr": "Confirmer le mot de passe" },
    { "key": "auth.register.confirmPasswordPlaceholder", "en": "Confirm password", "es": "Confirmar contraseña", "fr": "Confirmer le mot de passe" },
    { "key": "auth.register.submitting", "en": "Creating account...", "es": "Creando cuenta...", "fr": "Création du compte..." },
    { "key": "auth.register.submit", "en": "Create", "es": "Crear", "fr": "Créer" },
    { "key": "auth.register.alreadyHaveAccount", "en": "Already have an account?", "es": "¿Ya tienes una cuenta?", "fr": "Vous avez déjà un compte ?" },
    { "key": "auth.register.signInLink", "en": "Sign in", "es": "Iniciar sesión", "fr": "Se connecter" },
    { "key": "auth.login.title", "en": "Sign in", "es": "Iniciar sesión", "fr": "Se connecter" },
    { "key": "auth.login.emailLabel", "en": "Email", "es": "Correo electrónico", "fr": "E-mail" },
    { "key": "auth.login.emailPlaceholder", "en": "Email", "es": "Correo electrónico", "fr": "E-mail" },
    { "key": "auth.login.passwordLabel", "en": "Password", "es": "Contraseña", "fr": "Mot de passe" },
    { "key": "auth.login.passwordPlaceholder", "en": "Password", "es": "Contraseña", "fr": "Mot de passe" },
    { "key": "auth.login.submitting", "en": "Signing in...", "es": "Iniciando sesión...", "fr": "Connexion en cours..." },
    { "key": "auth.login.submit", "en": "Sign in", "es": "Iniciar sesión", "fr": "Se connecter" },
    { "key": "auth.login.noAccount", "en": "No account?", "es": "¿No tienes cuenta?", "fr": "Pas de compte ?" },
    { "key": "auth.login.registerLink", "en": "Register", "es": "Registrarse", "fr": "S'inscrire" },
    { "key": "auth.intro.register.kicker", "en": "New Membership", "es": "Nueva membresía", "fr": "Nouvel abonnement" },
    { "key": "auth.intro.register.title", "en": "Join the club.", "es": "Únete al club.", "fr": "Rejoignez le club." },
    { "key": "auth.intro.register.body", "en": "Set your name on the ledger, claim your table and start playing rapid duels, quiet endgames and reckless attacks against friends or AI.", "es": "Pon tu nombre en el libro, reclama tu mesa y comienza a jugar duelos rápidos, finales tranquilos y ataques imprudentes contra amigos o IA.", "fr": "Inscrivez votre nom sur le registre, réclamez votre table et commencez à jouer des duels rapides, des fins de partie calmes et des attaques téméraires contre des amis ou l'IA." },
    { "key": "auth.intro.register.noteTitle", "en": "Entry standard", "es": "Estándar de entrada", "fr": "Critère d'entrée" },
    { "key": "auth.intro.register.noteBody", "en": "Bring a valid email, a solid alias and enough patience for your first opening mistake.", "es": "Trae un correo electrónico válido, un alias sólido y suficiente paciencia para tu primer error de apertura.", "fr": "Apportez un e-mail valide, un alias solide et suffisamment de patience pour votre première erreur d'ouverture." },
    { "key": "auth.intro.login.kicker", "en": "Members Entrance", "es": "Entrada de miembros", "fr": "Entrée des membres" },
    { "key": "auth.intro.login.title", "en": "Return to the board.", "es": "Regresa al tablero.", "fr": "Retournez au plateau." },
    { "key": "auth.intro.login.body", "en": "Pick up unfinished rivalries, review your last games and step back into a room that looks like it has been waiting for you all evening...", "es": "Retoma rivalidades inconclusas, revisa tus últimas partidas y vuelve a una habitación que parece haberte estado esperando toda la noche...", "fr": "Reprenez les rivalités inachevées, revoyez vos dernières parties et retournez dans une pièce qui semble vous avoir attendu toute la soirée..." },
    { "key": "auth.intro.login.noteTitle", "en": "House note", "es": "Nota de la casa", "fr": "Nota de la maison" },
    { "key": "auth.intro.login.noteBody", "en": "Best experienced with coffee nearby and your queen protected.", "es": "Se disfruta mejor con café cerca y tu reina protegida.", "fr": "A savourer avec un café à proximité et votre reine protégée." },
    { "key": "friends.info.kicker", "en": "Friends List", "es": "Lista de amigos", "fr": "Liste d'amis" },
    { "key": "friends.info.title", "en": "Let's make some \"friends\".", "es": "Hagamos algunos \"amigos\".", "fr": "Faisons-nous des \"amis\"." },
    { "key": "friends.info.description", "en": "Keep your favorite rivals close, see who is online, and turn quiet names into the next game waiting across the board.", "es": "Mantén cerca a tus rivales favoritos, mira quién está en línea y convierte nombres tranquilos en el próximo juego que te espera en el tablero.", "fr": "Gardez vos rivaux préférés à proximité, voyez qui est en ligne et transformez des noms discrets en votre prochaine partie qui vous attend de l'autre côté du plateau." },
    { "key": "friends.info.note_title", "en": "House note", "es": "Nota de la casa", "fr": "Note de la maison" },
    { "key": "friends.info.note_desc", "en": "Friend requests stay quiet until accepted. Direct challenges are still a rumor in the back office, so keep your rivals close for now.", "es": "Las solicitudes de amistad permanecen en silencio hasta que se aceptan. Los desafíos directos aún son un rumor en la trastienda, así que mantén cerca a tus rivales por ahora.", "fr": "Les demandes d'amis restent silencieuses jusqu'à ce qu'elles soient acceptées. Les défis directs ne sont encore qu'une rumeur dans l'arrière-boutique, alors gardez vos rivaux à proximité pour l'instant." },
    { "key": "friends.list.title", "en": "Your friends", "es": "Tus amigos", "fr": "Vos amis" },
    { "key": "friends.list.loading", "en": "Loading friends...", "es": "Cargando amigos...", "fr": "Chargement des amis..." },
    { "key": "friends.list.status_online", "en": "Online", "es": "En línea", "fr": "En ligne" },
    { "key": "friends.list.status_offline", "en": "Offline", "es": "Desconectado", "fr": "Hors ligne" },
    { "key": "friends.list.remove_btn", "en": "Remove", "es": "Eliminar", "fr": "Retirer" },
    { "key": "friends.list.empty", "en": "No friends yet", "es": "Aún no tienes amigos", "fr": "Pas encore d'amis" },
    { "key": "friends.modal.default_friend", "en": "this friend", "es": "este amigo", "fr": "cet ami" },
    { "key": "friends.modal.title", "en": "Remove friend?", "es": "¿Eliminar amigo?", "fr": "Supprimer l'ami ?" },
    { "key": "friends.modal.copy", "en": "Remove {name} from your friends list?", "es": "¿Eliminar a {name} de tu lista de amigos?", "fr": "Supprimer {name} de votre liste d'amis ?" },
    { "key": "friends.modal.cancel", "en": "Cancel", "es": "Cancelar", "fr": "Annuler" },
    { "key": "friends.modal.removing", "en": "Removing...", "es": "Eliminando...", "fr": "Suppression..." },
    { "key": "friends.modal.remove", "en": "Remove", "es": "Eliminar", "fr": "Supprimer" },
    { "key": "friends.requests.title", "en": "Requests", "es": "Solicitudes", "fr": "Demandes" },
    { "key": "friends.requests.refresh", "en": "Refresh", "es": "Actualizar", "fr": "Actualiser" },
    { "key": "friends.requests.incoming", "en": "Incoming", "es": "Entrantes", "fr": "Entrantes" },
    { "key": "friends.requests.status_online", "en": "Online", "es": "En línea", "fr": "En ligne" },
    { "key": "friends.requests.status_offline", "en": "Offline", "es": "Desconectado", "fr": "Hors ligne" },
    { "key": "friends.requests.accept", "en": "Accept", "es": "Aceptar", "fr": "Accepter" },
    { "key": "friends.requests.reject", "en": "Reject", "es": "Rechazar", "fr": "Refuser" },
    { "key": "friends.requests.no_incoming", "en": "No incoming requests", "es": "No hay solicitudes entrantes", "fr": "Aucune demande entrante" },
    { "key": "friends.requests.outgoing", "en": "Outgoing", "es": "Salientes", "fr": "Sortantes" },
    { "key": "friends.requests.pending", "en": "Pending", "es": "Pendiente", "fr": "En attente" },
    { "key": "friends.requests.no_pending", "en": "No pending requests", "es": "No hay solicitudes pendientes", "fr": "Aucune demande en attente" },
    { "key": "friends.search.title", "en": "Find players", "es": "Buscar jugadores", "fr": "Trouver des joueurs" },
    { "key": "friends.search.aria_label", "en": "Search players by username or display name", "es": "Buscar jugadores por nombre de usuario o nombre visible", "fr": "Rechercher des joueurs par nom d'utilisateur ou nom d'affichage" },
    { "key": "friends.search.placeholder", "en": "Username or display name", "es": "Nombre de usuario o nombre visible", "fr": "Nom d'utilisateur ou d'affichage" },
    { "key": "friends.search.btn_searching", "en": "Searching...", "es": "Buscando...", "fr": "Recherche..." },
    { "key": "friends.search.btn", "en": "Search", "es": "Buscar", "fr": "Rechercher" },
    { "key": "friends.search.status_online", "en": "Online", "es": "En línea", "fr": "En ligne" },
    { "key": "friends.search.status_offline", "en": "Offline", "es": "Desconectado", "fr": "Hors ligne" },
    { "key": "friends.search.add_btn", "en": "Add", "es": "Añadir", "fr": "Ajouter" },
    { "key": "friends.search.no_players", "en": "No players found", "es": "No se encontraron jugadores", "fr": "Aucun joueur trouvé" },
    { "key": "history.kicker", "en": "Archive", "es": "Archivo", "fr": "Archives" },
    { "key": "history.title", "en": "Match History", "es": "Historial de partidas", "fr": "Historique des matchs" },
    { "key": "history.desc", "en": "Recent completed and interrupted games from your account timeline.", "es": "Partidas recientes completadas e interrumpidas de la línea de tiempo de tu cuenta.", "fr": "Parties récentes terminées et interrompues dans l'historique de votre compte." },
    { "key": "history.total_games", "en": "Total games", "es": "Total de partidas", "fr": "Total des parties" },
    { "key": "history.last_result", "en": "Last result", "es": "Último resultado", "fr": "Dernier résultat" },
    { "key": "history.list.unknown", "en": "Unknown", "es": "Desconocido", "fr": "Inconnu" },
    { "key": "history.list.you", "en": "You", "es": "Tú", "fr": "Vous" },
    { "key": "history.list.loading", "en": "Loading match history...", "es": "Cargando el historial de partidas...", "fr": "Chargement de l'historique des matchs..." },
    { "key": "history.list.retry", "en": "Retry", "es": "Reintentar", "fr": "Réessayer" },
    { "key": "history.list.no_games", "en": "No games recorded yet.", "es": "Aún no hay partidas registradas.", "fr": "Aucune partie enregistrée pour le moment." },
    { "key": "history.list.timeline", "en": "Timeline", "es": "Línea de tiempo", "fr": "Chronologie" },
    { "key": "history.list.game_id", "en": "Game #{id}", "es": "Partida #{id}", "fr": "Partie #{id}" },
    { "key": "history.list.white", "en": "White", "es": "Blancas", "fr": "Blancs" },
    { "key": "history.list.black", "en": "Black", "es": "Negras", "fr": "Noirs" },
    { "key": "leaderboard.unknown_player", "en": "Unknown player", "es": "Jugador desconocido", "fr": "Joueur inconnu" },
    { "key": "leaderboard.unknown_username", "en": "unknown", "es": "desconocido", "fr": "inconnu" },
    { "key": "leaderboard.rating", "en": "Rating", "es": "Clasificación", "fr": "Classement" },
    { "key": "leaderboard.kicker", "en": "Ranking", "es": "Clasificación", "fr": "Classement" },
    { "key": "leaderboard.title", "en": "Leaderboard", "es": "Tabla de clasificación", "fr": "Classement" },
    { "key": "leaderboard.desc", "en": "Current standings sorted by rating across the club.", "es": "Clasificación actual ordenada por puntuación en todo el club.", "fr": "Classement actuel trié par note dans l'ensemble du club." },
    { "key": "leaderboard.players_count", "en": "Players", "es": "Jugadores", "fr": "Joueurs" },
    { "key": "leaderboard.top_rating", "en": "Top rating", "es": "Mejor puntuación", "fr": "Meilleure note" },
    { "key": "leaderboard.current_leader", "en": "Current leader", "es": "Líder actual", "fr": "Leader actuel" },
    { "key": "leaderboard.standings", "en": "Standings", "es": "Posiciones", "fr": "Classement" },
    { "key": "leaderboard.loading", "en": "Loading leaderboard...", "es": "Cargando clasificación...", "fr": "Chargement du classement..." },
    { "key": "leaderboard.retry", "en": "Retry", "es": "Reintentar", "fr": "Réessayer" },
    { "key": "leaderboard.empty", "en": "No ranking data available.", "es": "No hay datos de clasificación disponibles.", "fr": "Aucune donnée de classement disponible." },
    { "key": "action.resign", "en": "Resign", "es": "Renunciar", "fr": "Abandonner" },
    { "key": "color.white", "en": "White", "es": "Blanco", "fr": "Blanc" },
    { "key": "color.black", "en": "Black", "es": "Negro", "fr": "Noir" },
    { "key": "game.check", "en": "Check", "es": "Jaque", "fr": "Échec" },
    { "key": "game.move", "en": "Move", "es": "Mover", "fr": "Jouer" },
    { "key": "game.king_under_attack", "en": "King under attack", "es": "Rey bajo ataque", "fr": "Roi attaqué" },
    { "key": "game.opening_position", "en": "Opening position", "es": "Posición de apertura", "fr": "Position de départ" },
    { "key": "confirm.resign_question", "en": "Are you sure you want to resign?", "es": "¿Estás seguro de que quieres renunciar?", "fr": "Êtes-vous sûr de vouloir abandonner ?" },
    { "key": "action.cancel", "en": "Cancel", "es": "Cancelar", "fr": "Annuler" },
    { "key": "grace.opponent_disconnected", "en": "Opponent disconnected", "es": "Oponente desconectado", "fr": "Adversaire déconnecté" },
    { "key": "grace.forfeit_countdown", "en": "Forfeit countdown", "es": "Cuenta regresiva de abandono", "fr": "Compte à rebours de forfait" },
    { "key": "grace.resolving_result", "en": "Resolving result", "es": "Resolviendo resultado", "fr": "Résolution du résultat" },
    { "key": "opponent.playing_vs_ai", "en": "Playing vs AI", "es": "Jugando contra IA", "fr": "Jouant contre l'IA" },
    { "key": "opponent.offline", "en": "Offline", "es": "Desconectado", "fr": "Hors ligne" },
    { "key": "opponent.online", "en": "Online", "es": "En línea", "fr": "En ligne" },
    { "key": "game.room_number", "en": "Game Room ", "es": "Sala de juego ", "fr": "Salle de jeu " },
    { "key": "status.reconnecting", "en": "Reconnecting...", "es": "Reconectando...", "fr": "Reconnexion..." },
    { "key": "status.disconnected_server", "en": "Disconnected from server", "es": "Desconectado del servidor", "fr": "Déconnecté du serveur" },
    { "key": "info.duration", "en": "Duration: ", "es": "Duración: ", "fr": "Durée : " },
    { "key": "info.min", "en": " min", "es": " min", "fr": " min" },
    { "key": "info.opponent", "en": "Opponent: ", "es": "Oponente: ", "fr": "Adversaire : " },
    { "key": "status.loading", "en": "Loading...", "es": "Cargando...", "fr": "Chargement..." },
    { "key": "action.retry", "en": "Retry", "es": "Reintentar", "fr": "Réessayer" },
    { "key": "result.win", "en": "YOU WIN", "es": "GANASTE", "fr": "VOUS AVEZ GAGNÉ" },
    { "key": "result.lost", "en": "YOU LOST", "es": "PERDISTE", "fr": "VOUS AVEZ PERDU" },
    { "key": "result.draw", "en": "DRAW", "es": "EMPATE", "fr": "ÉGALITÉ" },
    { "key": "action.lobby", "en": "Lobby", "es": "Sala de espera", "fr": "Accueil" },
    { "key": "chat.player", "en": "Player", "es": "Jugador", "fr": "Joueur" },
    { "key": "chat.you", "en": "You", "es": "Tú", "fr": "Vous" },
    { "key": "chat.title", "en": "Chat", "es": "Chat", "fr": "Chat" },
    { "key": "chat.unavailable_ai", "en": "Chat unavailable in games against AI", "es": "Chat no disponible en juegos contra la IA", "fr": "Chat indisponible pour les parties contre l'IA" },
    { "key": "chat.empty", "en": "No new messages", "es": "No hay mensajes nuevos", "fr": "Aucun nouveau message" },
    { "key": "status.connected", "en": "Connected", "es": "Conectado", "fr": "Connecté" },
    { "key": "status.disconnected", "en": "Disconnected", "es": "Desconectado", "fr": "Déconnecté" },
    { "key": "chat.placeholder", "en": "Message", "es": "Mensaje", "fr": "Message" },
    { "key": "chat.aria_label", "en": "Chat message", "es": "Mensaje de chat", "fr": "Message du chat" },
    { "key": "chat.send", "en": "Send", "es": "Enviar", "fr": "Envoyer" },
    { "key": "legal.privacy.kicker", "en": "Legal", "es": "Legal", "fr": "Légal" },
    { "key": "legal.privacy.title", "en": "Privacy Policy", "es": "Política de privacidad", "fr": "Politique de confidentialité" },
    { "key": "legal.privacy.intro1", "en": "Last updated: June 2026. This Privacy Policy explains how", "es": "Última actualización: junio de 2026. Esta Política de privacidad explica cómo", "fr": "Dernière mise à jour : juin 2026. Cette politique de confidentialité explique comment" },
    { "key": "legal.privacy.intro_strong", "en": "Checkmate Club", "es": "Checkmate Club", "fr": "Checkmate Club" },
    { "key": "legal.privacy.intro2", "en": "(\"we\", \"us\", or \"our\") collects, uses, stores and protects information about you when you use our online chess platform. By registering an account or using the service, you agree to the practices described below.", "es": "(\"nosotros\", \"nos\" o \"nuestro\") recopila, utiliza, almacena y protege información sobre usted cuando utiliza nuestra plataforma de ajedrez en línea. Al registrar una cuenta o usar el servicio, acepta las prácticas descritas a continuación.", "fr": "(\"nous\", \"notre\" ou \"nos\") collecte, utilise, stocke et protège les informations vous concernant lorsque vous utilisez notre plateforme d'échecs en ligne. En créant un compte ou en utilisant le service, vous acceptez les pratiques décrites ci-dessous." },
    { "key": "legal.privacy.sec1_title", "en": "1. Information We Collect", "es": "1. Información que recopilamos", "fr": "1. Informations que nous collectons" },
    { "key": "legal.privacy.sec1_p1", "en": "When you create an account we collect the following personal data:", "es": "Cuando crea una cuenta, recopilamos los siguientes datos personales:", "fr": "Lorsque vous créez un compte, nous collectons les données personnelles suivantes :" },
    { "key": "legal.privacy.sec1_li1_strong", "en": "Account credentials:", "es": "Credenciales de la cuenta:", "fr": "Identifiants de compte :" },
    { "key": "legal.privacy.sec1_li1_text", "en": " username, display name, and a securely hashed password.", "es": " nombre de usuario, nombre para mostrar y una contraseña con hash seguro.", "fr": " nom d'utilisateur, nom d'affichage et un mot de passe haché de manière sécurisée." },
    { "key": "legal.privacy.sec1_li2_strong", "en": "Profile information:", "es": "Información de perfil:", "fr": "Informations de profil :" },
    { "key": "legal.privacy.sec1_li2_text", "en": " optional avatar image you choose to upload.", "es": " imagen de avatar opcional que elija cargar.", "fr": " image d'avatar facultative que vous choisissez de télécharger." },
    { "key": "legal.privacy.sec1_li3_strong", "en": "Game data:", "es": "Datos del juego:", "fr": "Données de jeu :" },
    { "key": "legal.privacy.sec1_li3_text", "en": " chess positions, move history, game results, and ELO ratings.", "es": " posiciones de ajedrez, historial de movimientos, resultados del juego y calificaciones ELO.", "fr": " positions d'échecs, historique des mouvements, résultats de jeu et classements ELO." },
    { "key": "legal.privacy.sec1_li4_strong", "en": "Connection metadata:", "es": "Metadatos de conexión:", "fr": "Métadonnées de connexion :" },
    { "key": "legal.privacy.sec1_li4_text", "en": " your online/offline status for the Friends feature.", "es": " su estado en línea/fuera de línea para la función Amigos.", "fr": " votre statut en ligne/hors ligne pour la fonctionnalité Amis." },
    { "key": "legal.privacy.sec1_p2_1", "en": "We do ", "es": "Nosotros ", "fr": "Nous ne " },
    { "key": "legal.privacy.not", "en": "not", "es": "no", "fr": "pas" },
    { "key": "legal.privacy.sec1_p2_2", "en": " collect your real name, physical address, phone number, or payment information. No payment processing takes place on this platform.", "es": " recopilamos su nombre real, dirección física, número de teléfono o información de pago. No se realiza ningún procesamiento de pagos en esta plataforma.", "fr": " collectons pas votre nom réel, adresse physique, numéro de téléphone ou informations de paiement. Aucun traitement de paiement n'a lieu sur cette plateforme." },
    { "key": "legal.privacy.sec2_title", "en": "2. How We Use Your Information", "es": "2. Cómo utilizamos su información", "fr": "2. Comment nous utilisons vos informations" },
    { "key": "legal.privacy.sec2_p1", "en": "Your data is used solely to operate the Checkmate Club service:", "es": "Sus datos se utilizan únicamente para operar el servicio Checkmate Club:", "fr": "Vos données sont utilisées uniquement pour faire fonctionner le service Checkmate Club :" },
    { "key": "legal.privacy.sec2_li1", "en": "Authenticate you and maintain your session securely using JWT tokens stored in browser session storage.", "es": "Autenticarlo y mantener su sesión de forma segura utilizando tokens JWT almacenados en el almacenamiento de sesión del navegador.", "fr": "Vous authentifier et maintenir votre session en toute sécurité à l'aide de jetons JWT stockés dans le stockage de session du navigateur." },
    { "key": "legal.privacy.sec2_li2", "en": "Render your profile, ELO ranking, and game history.", "es": "Renderizar su perfil, clasificación ELO e historial de juegos.", "fr": "Afficher votre profil, votre classement ELO et l'historique de vos parties." },
    { "key": "legal.privacy.sec2_li3", "en": "Match you with opponents via the matchmaking queue.", "es": "Emparejarlo con oponentes a través de la cola de emparejamiento.", "fr": "Vous associer à des adversaires via la file d'attente de matchmaking." },
    { "key": "legal.privacy.sec2_li4", "en": "Display your online status to users you have added as friends.", "es": "Mostrar su estado en línea a los usuarios que ha agregado como amigos.", "fr": "Afficher votre statut en ligne aux utilisateurs que vous avez ajoutés comme amis." },
    { "key": "legal.privacy.sec2_li5", "en": "Maintain chat logs within active game rooms, limited to the last 100 messages per room and held in memory only.", "es": "Mantener registros de chat dentro de las salas de juego activas, limitados a los últimos 100 mensajes por sala y mantenidos solo en la memoria.", "fr": "Conserver les journaux de discussion dans les salles de jeu actives, limités aux 100 derniers messages par salle et conservés en mémoire uniquement." },
    { "key": "legal.privacy.sec2_p2_1", "en": "We do ", "es": "Nosotros ", "fr": "Nous n'" },
    { "key": "legal.privacy.sec2_p2_2", "en": " use your data for advertising, profiling, or automated decision-making that produces legal or similarly significant effects.", "es": " utilizamos sus datos para publicidad, elaboración de perfiles o toma de decisiones automatizada que produzca efectos legales o significativos similares.", "fr": " utilisons pas vos données à des fins publicitaires, de profilage ou de prise de décision automatisée produisant des effets juridiques ou des effets significatifs similaires." },
    { "key": "legal.privacy.sec3_title", "en": "3. Data Storage and Retention", "es": "3. Almacenamiento y retención de datos", "fr": "3. Stockage et conservation des données" },
    { "key": "legal.privacy.sec3_p1", "en": "Account and game data are stored in a PostgreSQL database hosted within the same infrastructure as the application. Avatar images are stored on the server filesystem under a protected upload directory.", "es": "Los datos de la cuenta y del juego se almacenan en una base de datos PostgreSQL alojada en la misma infraestructura que la aplicación. Las imágenes de avatar se almacenan en el sistema de archivos del servidor bajo un directorio de carga protegido.", "fr": "Les données de compte et de jeu sont stockées dans une base de données PostgreSQL hébergée dans la même infrastructure que l'application. Les images d'avatar sont stockées sur le système de fichiers du serveur sous un répertoire de téléchargement protégé." },
    { "key": "legal.privacy.sec3_p2", "en": "We retain your account data for as long as your account is active. If you request deletion of your account, all associated personal data, including your profile, game records and avatar, will be permanently removed within 30 days of the request.", "es": "Conservamos los datos de su cuenta mientras su cuenta esté activa. Si solicita la eliminación de su cuenta, todos los datos personales asociados, incluido su perfil, registros de juego y avatar, se eliminarán permanentemente dentro de los 30 días posteriores a la solicitud.", "fr": "Nous conservons les données de votre compte tant que votre compte est actif. Si vous demandez la suppression de votre compte, toutes les données personnelles associées, y compris votre profil, vos enregistrements de jeu et votre avatar, seront définitivement supprimées dans les 30 jours suivant la demande." },
    { "key": "legal.privacy.sec4_title", "en": "4. Cookies and Session Storage", "es": "4. Cookies y almacenamiento de sesión", "fr": "4. Cookies et stockage de session" },
    { "key": "legal.privacy.sec4_p1_1", "en": "Checkmate Club does ", "es": "Checkmate Club ", "fr": "Checkmate Club n'" },
    { "key": "legal.privacy.sec4_p1_2", "en": " use browser cookies for authentication. Access tokens and refresh tokens are stored exclusively in ", "es": " utiliza cookies del navegador para la autenticación. Los tokens de acceso y los tokens de actualización se almacenan exclusivamente en ", "fr": " utilise pas de cookies de navigateur pour l'authentification. Les jetons d'accès et les jetons d'actualisation sont stockés exclusivement dans " },
    { "key": "legal.privacy.sec4_p1_3", "en": ", which is automatically cleared when you close the browser tab or window.", "es": ", que se borra automáticamente cuando cierra la pestaña o ventana del navegador.", "fr": ", qui est automatiquement effacé lorsque vous fermez l'onglet ou la fenêtre du navigateur." },
    { "key": "legal.privacy.sec4_p2", "en": "No persistent tracking cookies or third-party analytics cookies are set by this application.", "es": "Esta aplicación no establece cookies de seguimiento persistentes ni cookies de análisis de terceros.", "fr": "Aucun cookie de suivi persistant ou cookie d'analyse tiers n'est défini par cette application." },
    { "key": "legal.privacy.sec5_title", "en": "5. Third-Party Services", "es": "5. Servicios de terceros", "fr": "5. Services tiers" },
    { "key": "legal.privacy.sec5_p1", "en": "This platform does not integrate third-party advertising networks, social login providers, analytics SDKs, or data brokers. No personal data is shared with, sold to, or transferred to any external party.", "es": "Esta plataforma no integra redes publicitarias de terceros, proveedores de inicio de sesión social, SDK de análisis o corredores de datos. Ningún dato personal se comparte, se vende ni se transfiere a terceros externos.", "fr": "Cette plateforme n'intègre pas de réseaux publicitaires tiers, de fournisseurs de connexion sociale, de SDK d'analyse ou de courtiers en données. Aucune donnée personnelle n'est partagée, vendue ou transférée à une partie externe." },
    { "key": "legal.privacy.sec6_title", "en": "6. Your Rights", "es": "6. Sus derechos", "fr": "6. Vos droits" },
    { "key": "legal.privacy.sec6_p1", "en": "Depending on your jurisdiction you may have rights regarding your personal data, including the right to access, correct, or delete it.", "es": "Dependiendo de su jurisdicción, puede tener derechos con respecto a sus datos personales, incluido el derecho a acceder, corregir o eliminar los mismos.", "fr": "Selon votre juridiction, vous pouvez avoir des droits concernant vos données personnelles, y compris le droit d'y accéder, de les corriger ou de les supprimer." },
    { "key": "legal.privacy.sec6_li1_strong", "en": "Access / Correction:", "es": "Acceso / Corrección:", "fr": "Accès / Correction :" },
    { "key": "legal.privacy.sec6_li1_text", "en": " Update your display name and avatar directly from your Profile page.", "es": " Actualice su nombre para mostrar y avatar directamente desde su página de perfil.", "fr": " Mettez à jour votre nom d'affichage et votre avatar directement depuis votre page de profil." },
    { "key": "legal.privacy.sec6_li2_strong", "en": "Deletion:", "es": "Eliminación:", "fr": "Suppression :" },
    { "key": "legal.privacy.sec6_li2_text", "en": " Contact us to request complete account deletion.", "es": " Contáctenos para solicitar la eliminación completa de la cuenta.", "fr": " Contactez-nous pour demander la suppression complète du compte." },
    { "key": "legal.privacy.sec6_li3_strong", "en": "Data portability:", "es": "Portabilidad de datos:", "fr": "Portabilité des données :" },
    { "key": "legal.privacy.sec6_li3_text", "en": " You may request an export of your game history in JSON format.", "es": " Puede solicitar una exportación de su historial de juegos en formato JSON.", "fr": " Vous pouvez demander une exportation de l'historique de vos jeux au format JSON." },
    { "key": "legal.privacy.sec7_title", "en": "7. Security", "es": "7. Seguridad", "fr": "7. Sécurité" },
    { "key": "legal.privacy.sec7_p1", "en": "We take reasonable technical measures to protect your data:", "es": "Tomamos medidas técnicas razonables para proteger sus datos:", "fr": "Nous prenons des mesures techniques raisonnables pour protéger vos données :" },
    { "key": "legal.privacy.sec7_li1", "en": "Passwords are hashed using bcrypt before storage.", "es": "Las contraseñas se codifican utilizando bcrypt antes del almacenamiento.", "fr": "Les mots de passe sont hachés à l'aide de bcrypt avant le stockage." },
    { "key": "legal.privacy.sec7_li2", "en": "All API communication is intended to be served over HTTPS in production.", "es": "Toda la comunicación de la API está destinada a ser servida a través de HTTPS en producción.", "fr": "Toute la communication de l'API est destinée à être servie via HTTPS en production." },
    { "key": "legal.privacy.sec7_li3", "en": "JWT access tokens have a short expiry and are not stored in cookies.", "es": "Los tokens de acceso JWT tienen un vencimiento breve y no se almacenan en cookies.", "fr": "Les jetons d'accès JWT ont une courte expiration et ne sont pas stockés dans des cookies." },
    { "key": "legal.privacy.sec7_li4", "en": "Avatar upload filenames are sanitized and stored outside the web root.", "es": "Los nombres de archivo de carga de avatar se desinfectan y almacenan fuera de la raíz web.", "fr": "Les noms de fichiers de téléchargement d'avatar sont nettoyés et stockés en dehors de la racine Web." },
    { "key": "legal.privacy.sec7_p2", "en": "No system is perfectly secure. If you discover a vulnerability, please report it responsibly before public disclosure.", "es": "Ningún sistema es perfectamente seguro. Si descubre una vulnerabilidad, infórmelo de manera responsable antes de la divulgación pública.", "fr": "Aucun système n'est parfaitement sécurisé. Si vous découvrez une vulnérabilité, veuillez la signaler de manière responsable avant toute divulgation publique." },
    { "key": "legal.privacy.sec8_title", "en": "8. Children's Privacy", "es": "8. Privacidad de los niños", "fr": "8. Confidentialité des enfants" },
    { "key": "legal.privacy.sec8_p1", "en": "Checkmate Club is not directed at children under the age of 13. We do not knowingly collect personal data from children under 13. If you believe a child has provided us with personal information, please contact us and we will delete it promptly.", "es": "Checkmate Club no está dirigido a niños menores de 13 años. No recopilamos a sabiendas datos personales de niños menores de 13 años. Si cree que un niño nos ha proporcionado información personal, comuníquese con nosotros y la eliminaremos de inmediato.", "fr": "Checkmate Club n'est pas destiné aux enfants de moins de 13 ans. Nous ne collectons pas sciemment de données personnelles auprès d'enfants de moins de 13 ans. Si vous pensez qu'un enfant nous a fourni des informations personnelles, veuillez nous contacter et nous les supprimerons rapidement." },
    { "key": "legal.privacy.sec9_title", "en": "9. Changes to This Policy", "es": "9. Cambios a esta Política", "fr": "9. Modifications de cette politique" },
    { "key": "legal.privacy.sec9_p1", "en": "We may update this Privacy Policy from time to time. The \"Last updated\" date at the top of this page will reflect the most recent revision. Continued use of the service after changes are published constitutes acceptance of the updated policy.", "es": "Podemos actualizar esta Política de privacidad de vez en cuando. La fecha de \"Última actualización\" en la parte superior de esta página reflejará la revisión más reciente. El uso continuado del servicio después de la publicación de los cambios constituye la aceptación de la política actualizada.", "fr": "Nous pouvons mettre à jour cette politique de confidentialité de temps à autre. La date de \"Dernière mise à jour\" en haut de cette page reflétera la révision la plus récente. L'utilisation continue du service après la publication des modifications constitue l'acceptation de la politique mise à jour." },
    { "key": "legal.privacy.sec10_title", "en": "10. Contact", "es": "10. Contacto", "fr": "10. Contact" },
    { "key": "legal.privacy.sec10_p1", "en": "If you have any questions, concerns, or requests relating to this Privacy Policy or your personal data, please contact the project team through your institution's official communication channels. This platform is a student project developed as part of the ft_transcendence curriculum at 42 School.", "es": "Si tiene alguna pregunta, inquietud o solicitud relacionada con esta Política de privacidad o sus datos personales, comuníquese con el equipo del proyecto a través de los canales de comunicación oficiales de su institución. Esta plataforma es un proyecto de estudiantes desarrollado como parte del plan de estudios ft_transcendence en 42 School.", "fr": "Si vous avez des questions, des préoccupations ou des demandes concernant cette politique de confidentialité ou vos données personnelles, veuillez contacter l'équipe du projet via les canaux de communication officiels de votre institution. Cette plateforme est un projet étudiant développé dans le cadre du cursus ft_transcendence à l'école 42." },
    { "key": "legal.terms.kicker", "en": "Legal", "es": "Legal", "fr": "Légal" },
    { "key": "legal.terms.title", "en": "Terms of Service", "es": "Términos de servicio", "fr": "Conditions d'utilisation" },
    { "key": "legal.terms.intro1", "en": "Last updated: June 2026. These Terms of Service (\"Terms\") govern your access to and use of ", "es": "Última actualización: junio de 2026. Estos Términos de servicio (\"Términos\") rigen su acceso y uso de ", "fr": "Dernière mise à jour : juin 2026. Ces conditions d'utilisation (« Conditions ») régissent votre accès et votre utilisation de " },
    { "key": "legal.terms.intro_strong", "en": "Checkmate Club", "es": "Checkmate Club", "fr": "Checkmate Club" },
    { "key": "legal.terms.intro2", "en": ", an online chess platform (\"Service\") developed as part of the ft_transcendence project at 42 School. By registering an account or using the Service you agree to be bound by these Terms.", "es": ", una plataforma de ajedrez en línea (\"Servicio\") desarrollada como parte del proyecto ft_transcendence en 42 School. Al registrar una cuenta o utilizar el Servicio, acepta estar sujeto a estos Términos.", "fr": ", une plateforme d'échecs en ligne (« Service ») développée dans le cadre du projet ft_transcendence à l'École 42. En créant un compte ou en utilisant le Service, vous acceptez d'être lié par ces Conditions." },
    { "key": "legal.terms.sec1_title", "en": "1. Acceptance of Terms", "es": "1. Aceptación de los Términos", "fr": "1. Acceptation des conditions" },
    { "key": "legal.terms.sec1_p1", "en": "By creating an account or otherwise accessing the Service, you confirm that you have read, understood, and agree to these Terms. If you do not agree, you must not use the Service. We reserve the right to update these Terms at any time; your continued use of the Service after an update constitutes acceptance of the revised Terms.", "es": "Al crear una cuenta o acceder al Servicio de otra manera, confirma que ha leído, comprendido y acepta estos Términos. Si no está de acuerdo, no debe utilizar el Servicio. Nos reservamos el derecho de actualizar estos Términos en cualquier momento; su uso continuado del Servicio después de una actualización constituye la aceptación de los Términos revisados.", "fr": "En créant un compte ou en accédant autrement au Service, vous confirmez que vous avez lu, compris et accepté ces Conditions. Si vous n'êtes pas d'accord, vous ne devez pas utiliser le Service. Nous nous réservons le droit de mettre à jour ces Conditions à tout moment ; votre utilisation continue du Service après une mise à jour constitue l'acceptation des Conditions révisées." },
    { "key": "legal.terms.sec2_title", "en": "2. Eligibility", "es": "2. Elegibilidad", "fr": "2. Éligibilité" },
    { "key": "legal.terms.sec2_p1", "en": "You must be at least 13 years old to use Checkmate Club. By using the Service you represent that you meet this requirement. If you are using the Service on behalf of an organisation, you represent that you have authority to bind that organisation to these Terms.", "es": "Debe tener al menos 13 años para utilizar Checkmate Club. Al utilizar el Servicio, usted declara que cumple con este requisito. Si utiliza el Servicio en nombre de una organización, declara que tiene autoridad para vincular a dicha organización a estos Términos.", "fr": "Vous devez avoir au moins 13 ans pour utiliser Checkmate Club. En utilisant le Service, vous déclarez que vous remplissez cette exigence. Si vous utilisez le Service au nom d'une organisation, vous déclarez que vous avez l'autorité pour lier cette organisation à ces Conditions." },
    { "key": "legal.terms.sec3_title", "en": "3. Account Registration", "es": "3. Registro de cuenta", "fr": "3. Inscription de compte" },
    { "key": "legal.terms.sec3_p1", "en": "To access most features you must register an account with a unique username and a secure password. You are responsible for:", "es": "Para acceder a la mayoría de las funciones, debe registrar una cuenta con un nombre de usuario único y una contraseña segura. Usted es responsable de:", "fr": "Pour accéder à la plupart des fonctionnalités, vous devez enregistrer un compte avec un nom d'utilisateur unique et un mot de passe sécurisé. Vous êtes responsable de :" },
    { "key": "legal.terms.sec3_li1", "en": "Providing accurate information during registration.", "es": "Proporcionar información precisa durante el registro.", "fr": "Fournir des informations exactes lors de l'inscription." },
    { "key": "legal.terms.sec3_li2", "en": "Keeping your password confidential and not sharing it with others.", "es": "Mantener su contraseña confidencial y no compartirla con otros.", "fr": "Garder votre mot de passe confidentiel et ne pas le partager avec d'autres." },
    { "key": "legal.terms.sec3_li3", "en": "All activity that occurs under your account, whether or not authorised by you.", "es": "Toda actividad que ocurra bajo su cuenta, esté o no autorizada por usted.", "fr": "Toute activité qui se produit sous votre compte, qu'elle soit ou non autorisée par vous." },
    { "key": "legal.terms.sec3_li4", "en": "Notifying us immediately if you suspect unauthorised access to your account.", "es": "Notificarnos inmediatamente si sospecha de acceso no autorizado a su cuenta.", "fr": "Nous informer immédiatement si vous soupçonnez un accès non autorisé à votre compte." },
    { "key": "legal.terms.sec3_p2", "en": "We reserve the right to suspend or terminate accounts that violate these Terms or that have been inactive for an extended period.", "es": "Nos reservamos el derecho de suspender o cancelar cuentas que violen estos Términos o que hayan estado inactivas durante un período prolongado.", "fr": "Nous nous réservons le droit de suspendre ou de fermer les comptes qui violent ces Conditions ou qui sont restés inactifs pendant une période prolongée." },
    { "key": "legal.terms.sec4_title", "en": "4. Acceptable Use", "es": "4. Uso aceptable", "fr": "4. Utilisation acceptable" },
    { "key": "legal.terms.sec4_p1", "en": "You agree to use the Service only for lawful purposes and in a manner consistent with fair play. The following conduct is strictly prohibited:", "es": "Usted acepta usar el Servicio solo para fines legales y de manera consistente con el juego limpio. La siguiente conducta está estrictamente prohibida:", "fr": "Vous acceptez de n'utiliser le Service qu'à des fins légales et d'une manière conforme au fair-play. Le comportement suivant est strictement interdit :" },
    { "key": "legal.terms.sec4_li1_strong", "en": "Cheating:", "es": "Hacer trampa:", "fr": "Tricherie :" },
    { "key": "legal.terms.sec4_li1_text", "en": " Using chess engines, bots, or third-party assistance tools during rated games.", "es": " Uso de motores de ajedrez, bots o herramientas de asistencia de terceros durante juegos clasificados.", "fr": " Utilisation de moteurs d'échecs, de robots ou d'outils d'assistance tiers lors de parties classées." },
    { "key": "legal.terms.sec4_li2_strong", "en": "Abuse:", "es": "Abuso:", "fr": "Abus :" },
    { "key": "legal.terms.sec4_li2_text", "en": " Harassing, threatening, or sending offensive messages to other users via the in-game chat.", "es": " Acosar, amenazar o enviar mensajes ofensivos a otros usuarios a través del chat del juego.", "fr": " Harceler, menacer ou envoyer des messages offensants à d'autres utilisateurs via le chat du jeu." },
    { "key": "legal.terms.sec4_li3_strong", "en": "Impersonation:", "es": "Suplantación:", "fr": "Usurpation d'identité :" },
    { "key": "legal.terms.sec4_li3_text", "en": " Creating accounts that impersonate other users or public figures.", "es": " Crear cuentas que se hacen pasar por otros usuarios o figuras públicas.", "fr": " Création de comptes usurpant l'identité d'autres utilisateurs ou de personnalités publiques." },
    { "key": "legal.terms.sec4_li4_strong", "en": "Exploitation:", "es": "Explotación:", "fr": "Exploitation :" },
    { "key": "legal.terms.sec4_li4_text", "en": " Deliberately exploiting bugs or vulnerabilities to gain an unfair advantage or disrupt the Service.", "es": " Explotar deliberadamente errores o vulnerabilidades para obtener una ventaja injusta o interrumpir el Servicio.", "fr": " Exploitation délibérée de bogues ou de vulnérabilités pour obtenir un avantage injuste ou perturber le Service." },
    { "key": "legal.terms.sec4_li5_strong", "en": "Unauthorised access:", "es": "Acceso no autorizado:", "fr": "Accès non autorisé :" },
    { "key": "legal.terms.sec4_li5_text", "en": " Attempting to access accounts, databases, or server resources that are not your own.", "es": " Intentar acceder a cuentas, bases de datos o recursos del servidor que no son suyos.", "fr": " Tentative d'accès à des comptes, des bases de données ou des ressources de serveur qui ne vous appartiennent pas." },
    { "key": "legal.terms.sec4_li6_strong", "en": "Automated scraping:", "es": "Extracción automatizada:", "fr": "Collecte automatisée :" },
    { "key": "legal.terms.sec4_li6_text", "en": " Using bots or scripts to collect user data without permission.", "es": " Uso de bots o scripts para recopilar datos de usuarios sin permiso.", "fr": " Utilisation de robots ou de scripts pour collecter des données utilisateur sans autorisation." },
    { "key": "legal.terms.sec4_li7_strong", "en": "Illegal content:", "es": "Contenido ilegal:", "fr": "Contenu illégal :" },
    { "key": "legal.terms.sec4_li7_text", "en": " Uploading avatar images or sending chat messages that contain illegal or prohibited content.", "es": " Cargar imágenes de avatar o enviar mensajes de chat que contengan contenido ilegal o prohibido.", "fr": " Téléchargement d'images d'avatar ou envoi de messages de chat contenant du contenu illégal ou interdit." },
    { "key": "legal.terms.sec4_p2", "en": "Violations may result in immediate account suspension or permanent ban without prior notice, at our sole discretion.", "es": "Las violaciones pueden resultar en la suspensión inmediata de la cuenta o prohibición permanente sin previo aviso, a nuestro exclusivo criterio.", "fr": "Les violations peuvent entraîner la suspension immédiate du compte ou une interdiction permanente sans préavis, à notre seule discrétion." },
    { "key": "legal.terms.sec5_title", "en": "5. Fair Play and ELO Rating", "es": "5. Juego limpio y clasificación ELO", "fr": "5. Fair-play et classement ELO" },
    { "key": "legal.terms.sec5_p1", "en": "Checkmate Club uses an ELO-based rating system to rank players. The integrity of the rating system relies on honest play. Intentionally losing games to manipulate your own or another player's ELO rating is prohibited and may result in account termination and ELO adjustment.", "es": "Checkmate Club utiliza un sistema de clasificación basado en ELO para clasificar a los jugadores. La integridad del sistema de clasificación se basa en el juego honesto. Perder juegos intencionalmente para manipular su propia clasificación ELO o la de otro jugador está prohibido y puede resultar en la cancelación de la cuenta y el ajuste de ELO.", "fr": "Checkmate Club utilise un système d'évaluation basé sur ELO pour classer les joueurs. L'intégrité du système de notation repose sur un jeu honnête. Perdre intentionnellement des parties pour manipuler votre propre classement ELO ou celui d'un autre joueur est interdit et peut entraîner la résiliation de votre compte et un ajustement ELO." },
    { "key": "legal.terms.sec5_p2", "en": "Abandoning games repeatedly without good reason is considered unsportsmanlike. The platform enforces a 30-second reconnection grace period; failure to reconnect results in a forfeit and an ELO penalty.", "es": "Abandonar juegos repetidamente sin una buena razón se considera antideportivo. La plataforma hace cumplir un período de gracia de reconexión de 30 segundos; no volver a conectarse resulta en una pérdida y una penalización de ELO.", "fr": "L'abandon répété de jeux sans raison valable est considéré comme antisportif. La plateforme applique un délai de grâce de reconnexion de 30 secondes ; le fait de ne pas se reconnecter entraîne un forfait et une pénalité ELO." },
    { "key": "legal.terms.sec6_title", "en": "6. User Content", "es": "6. Contenido del usuario", "fr": "6. Contenu utilisateur" },
    { "key": "legal.terms.sec6_p1", "en": "You retain ownership of content you submit to the Service, such as your avatar image. By uploading content, you grant us a non-exclusive, worldwide, royalty-free licence to store, display, and serve that content solely for the purpose of operating the Service.", "es": "Usted conserva la propiedad del contenido que envía al Servicio, como la imagen de su avatar. Al cargar contenido, nos otorga una licencia no exclusiva, mundial y libre de regalías para almacenar, mostrar y servir ese contenido con el único propósito de operar el Servicio.", "fr": "Vous conservez la propriété du contenu que vous soumettez au Service, tel que votre image d'avatar. En téléchargeant du contenu, vous nous accordez une licence non exclusive, mondiale et libre de droits pour stocker, afficher et diffuser ce contenu uniquement dans le but d'exploiter le Service." },
    { "key": "legal.terms.sec6_p2", "en": "You represent that you have the right to grant this licence and that your content does not infringe any third-party intellectual property rights. We reserve the right to remove any content that violates these Terms or applicable law.", "es": "Usted declara que tiene derecho a otorgar esta licencia y que su contenido no infringe ningún derecho de propiedad intelectual de terceros. Nos reservamos el derecho de eliminar cualquier contenido que viole estos Términos o la ley aplicable.", "fr": "Vous déclarez que vous avez le droit d'accorder cette licence et que votre contenu n'enfreint aucun droit de propriété intellectuelle de tiers. Nous nous réservons le droit de supprimer tout contenu qui viole ces Conditions ou la loi applicable." },
    { "key": "legal.terms.sec7_title", "en": "7. Intellectual Property", "es": "7. Propiedad intelectual", "fr": "7. Propriété intellectuelle" },
    { "key": "legal.terms.sec7_p1_1", "en": "The Checkmate Club platform, including its source code, design, and branding, is developed as an educational project under the ft_transcendence curriculum. The chess rules engine used by the platform is provided by the open-source ", "es": "La plataforma Checkmate Club, incluido su código fuente, diseño y marca, se desarrolla como un proyecto educativo bajo el plan de estudios ft_transcendence. El motor de reglas de ajedrez utilizado por la plataforma es proporcionado por la biblioteca de código abierto ", "fr": "La plateforme Checkmate Club, y compris son code source, sa conception et sa marque, est développée en tant que projet éducatif dans le cadre du cursus ft_transcendence. Le moteur de règles d'échecs utilisé par la plateforme est fourni par la bibliothèque open source " },
    { "key": "legal.terms.sec7_p1_strong", "en": "python-chess", "es": "python-chess", "fr": "python-chess" },
    { "key": "legal.terms.sec7_p1_2", "en": " library under the GPL-3.0 licence.", "es": " bajo la licencia GPL-3.0.", "fr": " sous la licence GPL-3.0." },
    { "key": "legal.terms.sec7_p2", "en": "Nothing in these Terms transfers any intellectual property rights to you beyond the limited right to use the Service as described herein.", "es": "Nada en estos Términos le transfiere ningún derecho de propiedad intelectual más allá del derecho limitado a usar el Servicio como se describe en este documento.", "fr": "Rien dans ces Conditions ne vous transfère de droits de propriété intellectuelle au-delà du droit limité d'utiliser le Service tel que décrit dans les présentes." },
    { "key": "legal.terms.sec8_title", "en": "8. Service Availability", "es": "8. Disponibilidad del servicio", "fr": "8. Disponibilité du service" },
    { "key": "legal.terms.sec8_p1", "en": "Checkmate Club is provided as-is and on an as-available basis. As a student project, the Service may be taken offline, modified, or discontinued at any time without notice. We do not guarantee continuous, uninterrupted, or error-free operation of the Service.", "es": "Checkmate Club se proporciona \"tal cual\" y \"según disponibilidad\". Como proyecto estudiantil, el Servicio puede desconectarse, modificarse o discontinuarse en cualquier momento sin previo aviso. No garantizamos el funcionamiento continuo, ininterrumpido o libre de errores del Servicio.", "fr": "Checkmate Club est fourni « en l'état » et « selon la disponibilité ». En tant que projet étudiant, le Service peut être mis hors ligne, modifié ou interrompu à tout moment sans préavis. Nous ne garantissons pas le fonctionnement continu, ininterrompu ou sans erreur du Service." },
    { "key": "legal.terms.sec9_title", "en": "9. Disclaimer of Warranties", "es": "9. Renuncia de garantías", "fr": "9. Exclusion de garanties" },
    { "key": "legal.terms.sec9_p1_1", "en": "To the maximum extent permitted by applicable law, the Service is provided ", "es": "En la medida máxima permitida por la ley aplicable, el Servicio se proporciona ", "fr": "Dans toute la mesure permise par la loi applicable, le Service est fourni " },
    { "key": "legal.terms.sec9_p1_strong", "en": "\"as is\"", "es": "\"tal cual\"", "fr": "« en l'état »" },
    { "key": "legal.terms.sec9_p1_2", "en": " without warranties of any kind, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement.", "es": " sin garantías de ningún tipo, ya sean expresas o implícitas, incluidas, entre otras, las garantías implícitas de comerciabilidad, idoneidad para un propósito particular y no infracción.", "fr": " sans garanties d'aucune sorte, expresses ou implicites, y compris, mais sans s'y limiter, les garanties implicites de qualité marchande, d'adéquation à un usage particulier et de non-contrefaçon." },
    { "key": "legal.terms.sec10_title", "en": "10. Limitation of Liability", "es": "10. Limitación de responsabilidad", "fr": "10. Limitation de responsabilité" },
    { "key": "legal.terms.sec10_p1", "en": "To the fullest extent permitted by law, the authors of Checkmate Club shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of or inability to use the Service.", "es": "En la máxima medida permitida por la ley, los autores de Checkmate Club no serán responsables de ningún daño indirecto, incidental, especial, consecuente o punitivo que surja de o esté relacionado con su uso o incapacidad de usar el Servicio.", "fr": "Dans toute la mesure permise par la loi, les auteurs de Checkmate Club ne seront pas responsables des dommages indirects, accessoires, spéciaux, consécutifs ou punitifs découlant de ou liés à votre utilisation ou incapacité d'utiliser le Service." },
    { "key": "legal.terms.sec10_p2", "en": "Because this is a student project with no commercial activity, our total aggregate liability to you for any claim arising from these Terms or your use of the Service shall not exceed zero euros (EUR 0).", "es": "Debido a que este es un proyecto de estudiantes sin actividad comercial, nuestra responsabilidad total agregada hacia usted por cualquier reclamo que surja de estos Términos o de su uso del Servicio no excederá los cero euros (0 EUR).", "fr": "Étant donné qu'il s'agit d'un projet étudiant sans activité commerciale, notre responsabilité globale totale envers vous pour toute réclamation découlant de ces Conditions ou de votre utilisation du Service ne dépassera pas zéro euro (0 EUR)." },
    { "key": "legal.terms.sec11_title", "en": "11. Governing Law", "es": "11. Ley aplicable", "fr": "11. Droit applicable" },
    { "key": "legal.terms.sec11_p1", "en": "These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which the project is hosted, without regard to its conflict-of-law provisions.", "es": "Estos Términos se regirán e interpretarán de acuerdo con las leyes de la jurisdicción en la que se aloja el proyecto, sin tener en cuenta sus disposiciones sobre conflictos de leyes.", "fr": "Ces Conditions seront régies et interprétées conformément aux lois de la juridiction dans laquelle le projet est hébergé, sans égard à ses dispositions en matière de conflits de lois." },
    { "key": "legal.terms.sec12_title", "en": "12. Contact", "es": "12. Contacto", "fr": "12. Contact" },
    { "key": "legal.terms.sec12_p1", "en": "For any questions about these Terms of Service, please contact the project team through your institution's official communication channels. This Service is a student project developed as part of the ft_transcendence curriculum at 42 School.", "es": "Si tiene alguna pregunta sobre estos Términos de servicio, comuníquese con el equipo del proyecto a través de los canales de comunicación oficiales de su institución. Este Servicio es un proyecto de estudiantes desarrollado como parte del plan de estudios ft_transcendence en 42 School.", "fr": "Pour toute question concernant ces Conditions d'utilisation, veuillez contacter l'équipe du projet via les canaux de communication officiels de votre institution. Ce Service est un projet étudiant développé dans le cadre du cursus ft_transcendence à l'École 42." },
    { "key": "lobby.confirm_resign", "en": "Resign this game? Your opponent will win.", "es": "¿Abandonar este juego? Tu oponente ganará.", "fr": "Abandonner cette partie ? Votre adversaire gagnera." },
    { "key": "lobby.cancel", "en": "Cancel", "es": "Cancelar", "fr": "Annuler" },
    { "key": "lobby.resign", "en": "Resign", "es": "Abandonar", "fr": "Abandonner" },
    { "key": "lobby.active.kicker", "en": "Resume", "es": "Reanudar", "fr": "Reprendre" },
    { "key": "lobby.active.title", "en": "Active game", "es": "Juego activo", "fr": "Partie active" },
    { "key": "lobby.active.copy", "en": "You have an unfinished game. Return to the room before the clock gets ideas.", "es": "Tienes un juego sin terminar. Regresa a la sala antes de que el reloj se agote.", "fr": "Vous avez une partie inachevée. Retournez dans la salle avant que l'horloge ne s'épuise." },
    { "key": "lobby.active.resume_btn", "en": "Resume game", "es": "Reanudar juego", "fr": "Reprendre la partie" },
    { "key": "lobby.active.resign_btn", "en": "Resign game", "es": "Abandonar juego", "fr": "Abandonner la partie" },
    { "key": "lobby.active.resigning", "en": "Resigning...", "es": "Abandonando...", "fr": "Abandon en cours..." },
    { "key": "lobby.ai.title", "en": "Play vs AI", "es": "Jugar contra IA", "fr": "Jouer contre l'IA" },
    { "key": "lobby.ai.copy", "en": "Warm up with the engine and choose how sharp the room should feel.", "es": "Calienta con el motor y elige cuán aguda debe sentirse la habitación.", "fr": "Échauffez-vous avec le moteur et choisissez la difficulté." },
    { "key": "lobby.ai.difficulty_label", "en": "AI difficulty", "es": "Dificultad de la IA", "fr": "Difficulté de l'IA" },
    { "key": "lobby.ai.diff_easy", "en": "Easy", "es": "Fácil", "fr": "Facile" },
    { "key": "lobby.ai.diff_medium", "en": "Medium", "es": "Medio", "fr": "Moyen" },
    { "key": "lobby.ai.diff_hard", "en": "Hard", "es": "Difícil", "fr": "Difficile" },
    { "key": "lobby.ai.time_label", "en": "Time control", "es": "Control de tiempo", "fr": "Contrôle du temps" },
    { "key": "lobby.ai.minutes", "en": "minutes", "es": "minutos", "fr": "minutes" },
    { "key": "lobby.ai.start_btn", "en": "Start AI game", "es": "Iniciar juego con IA", "fr": "Démarrer partie IA" },
    { "key": "lobby.hero.kicker", "en": "Game Lobby", "es": "Sala de juegos", "fr": "Salle de jeux" },
    { "key": "lobby.hero.title", "en": "Choose your table.", "es": "Elige tu mesa.", "fr": "Choisissez votre table." },
    { "key": "lobby.hero.copy", "en": "Join live matchmaking, start a training game against the engine, or resume the board you left waiting.", "es": "Únete al emparejamiento en vivo, comienza un juego de entrenamiento contra el motor o reanuda el tablero que dejaste en espera.", "fr": "Rejoignez le matchmaking en direct, commencez une partie d'entraînement contre le moteur ou reprenez la partie que vous avez laissée en attente." },
    { "key": "lobby.status.status", "en": "Status", "es": "Estado", "fr": "Statut" },
    { "key": "lobby.status.queue_spot", "en": "Queue spot", "es": "Lugar en la cola", "fr": "Place dans la file" },
    { "key": "lobby.status.time_control", "en": "Time control", "es": "Control de tiempo", "fr": "Contrôle du temps" },
    { "key": "lobby.status.min", "en": "min", "es": "min", "fr": "min" },
    { "key": "lobby.matchmaking.title", "en": "Play 1v1", "es": "Jugar 1v1", "fr": "Jouer 1v1" },
    { "key": "lobby.matchmaking.copy", "en": "Enter the queue and move into a real-time room when a rival appears.", "es": "Entra a la cola y pasa a una sala en tiempo real cuando aparezca un rival.", "fr": "Entrez dans la file d'attente et rejoignez une salle en temps réel lorsqu'un rival apparaît." },
    { "key": "lobby.matchmaking.time_label", "en": "Time control", "es": "Control de tiempo", "fr": "Contrôle du temps" },
    { "key": "lobby.matchmaking.minutes", "en": "minutes", "es": "minutos", "fr": "minutes" },
    { "key": "lobby.matchmaking.join", "en": "Join matchmaking", "es": "Unirse al emparejamiento", "fr": "Rejoindre le matchmaking" },
    { "key": "lobby.matchmaking.waiting", "en": "Waiting...", "es": "Esperando...", "fr": "En attente..." },
    { "key": "lobby.matchmaking.leave", "en": "Leave queue", "es": "Salir de la cola", "fr": "Quitter la file" },
    { "key": "profile.achievements.error_load", "en": "Failed to load achievements", "es": "Error al cargar los logros", "fr": "Échec du chargement des succès" },
    { "key": "profile.achievements.kicker", "en": "Achievements", "es": "Logros", "fr": "Succès" },
    { "key": "profile.achievements.title", "en": "Badges of Honor", "es": "Insignias de Honor", "fr": "Insignes d'honneur" },
    { "key": "profile.achievements.copy", "en": "Complete challenges to unlock badges for your profile.", "es": "Completa desafíos para desbloquear insignias para tu perfil.", "fr": "Terminez des défis pour débloquer des insignes pour votre profil." },
    { "key": "profile.achievements.loading", "en": "Loading achievements...", "es": "Cargando logros...", "fr": "Chargement des succès..." },
    { "key": "profile.achievements.completed", "en": "Completed", "es": "Completado", "fr": "Terminé" },
    { "key": "profile.achievements.locked", "en": "Locked", "es": "Bloqueado", "fr": "Verrouillé" },
    { "key": "profile.loading", "en": "Loading profile...", "es": "Cargando perfil...", "fr": "Chargement du profil..." },
    { "key": "profile.retry", "en": "Retry", "es": "Reintentar", "fr": "Réessayer" },
    { "key": "profile.tabs.settings", "en": "Profile Settings", "es": "Configuración de perfil", "fr": "Paramètres du profil" },
    { "key": "profile.tabs.achievements", "en": "Achievements", "es": "Logros", "fr": "Succès" },
    { "key": "profile.settings.kicker", "en": "Profile Settings", "es": "Configuración de perfil", "fr": "Paramètres du profil" },
    { "key": "profile.settings.title", "en": "Profile", "es": "Perfil", "fr": "Profil" },
    { "key": "profile.avatar.help", "en": "JPEG, PNG or WebP. Maximum size: 2 MB.", "es": "JPEG, PNG o WebP. Tamaño máximo: 2 MB.", "fr": "JPEG, PNG ou WebP. Taille maximale : 2 Mo." },
    { "key": "profile.avatar.uploading", "en": "Uploading...", "es": "Subiendo...", "fr": "Téléchargement..." },
    { "key": "profile.avatar.change_btn", "en": "Change avatar", "es": "Cambiar avatar", "fr": "Changer d'avatar" },
    { "key": "profile.edit.display_name_label", "en": "Display name", "es": "Nombre para mostrar", "fr": "Nom d'affichage" },
    { "key": "profile.edit.display_name_placeholder", "en": "Display name", "es": "Nombre para mostrar", "fr": "Nom d'affichage" },
    { "key": "profile.edit.save_btn", "en": "Save profile", "es": "Guardar perfil", "fr": "Enregistrer le profil" },
    { "key": "profile.edit.saving", "en": "Saving...", "es": "Guardando...", "fr": "Enregistrement..." },
    { "key": "profile.rank.novice", "en": "Novice", "es": "Novato", "fr": "Novice" },
    { "key": "profile.rank.intermediate", "en": "Intermediate", "es": "Intermedio", "fr": "Intermédiaire" },
    { "key": "profile.rank.advanced", "en": "Avanzado", "es": "Avanzado", "fr": "Avancé" },
    { "key": "profile.rank.master", "en": "Master", "es": "Maestro", "fr": "Maître" },
    { "key": "profile.summary.avatar_alt", "en": "Avatar of", "es": "Avatar de", "fr": "Avatar de" },
    { "key": "profile.summary.user", "en": "user", "es": "usuario", "fr": "utilisateur" },
    { "key": "profile.summary.level", "en": "Level", "es": "Nivel", "fr": "Niveau" },
    { "key": "profile.summary.to_next_level", "en": "to next level", "es": "al siguiente nivel", "fr": "au niveau suivant" }
]

for item in data:
    if "key" in item:
        en[item["key"]] = item["en"]
        es[item["key"]] = item["es"]
        fr[item["key"]] = item["fr"]

content = f"""export const translations = {{
  en: {json.dumps(en, indent=4)},
  es: {json.dumps(es, indent=4)},
  fr: {json.dumps(fr, indent=4)}
}};
"""

with open("/workspace/utils/translations.js", "w") as f:
    f.write(content)

print("Translations written successfully!")
